name: CI Workflow for Criteria 3

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sml

    steps:
      - name: Debug Docker Hub Username
        run: |
          echo "Docker Hub Username: ${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "Docker Hub Access Token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r criteria_3/Workflow-CI/MLProject/requirements.txt

      - name: Run MLflow project
        run: |
          python criteria_3/Workflow-CI/MLProject/modelling.py

      - name: Get latest MLflow run_id
        run: |
          # Find the latest experiment directory
          LATEST_EXPERIMENT=$(ls -td criteria_3/Workflow-CI/MLProject/mlruns/*/ | head -n 1 | xargs basename)
          if [ -z "$LATEST_EXPERIMENT" ]; then
            echo "No experiment directories found. Exiting."
            exit 1
          fi

          # Find the latest run ID in the latest experiment
          LATEST_EXPERIMENT_PATH="criteria_3/Workflow-CI/MLProject/mlruns/$LATEST_EXPERIMENT"
          RUN_ID=$(ls -td "$LATEST_EXPERIMENT_PATH"/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
          if [ -z "$RUN_ID" ]; then
            echo "No valid Run ID found in experiment $LATEST_EXPERIMENT. Exiting."
            exit 1
          fi

          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "EXPERIMENT_ID=$LATEST_EXPERIMENT" >> $GITHUB_ENV
          echo "Latest experiment ID: $LATEST_EXPERIMENT"
          echo "Latest run ID: $RUN_ID"

      - name: Build Docker Model
        run: |
          export MLFLOW_TRACKING_URI="file://$(pwd)/criteria_3/Workflow-CI/MLProject/mlruns"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "insurance_model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag insurance_model ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest
